### ISSUE TITLE
Output of trajectory along with meteorological data

### ISSUE THREAD

**Issue by jia-11** [rich-iannone/SplitR#1]
Great work!!
Is it possible to add meteorological data along the out put of trajectory in future version? Thanks!

**Comment by rich-iannone** [comment]
@jia-11 This should be trivial but it requires a bit of work. I think it would be a great feature!

**Comment by rich-iannone** [comment]
@jia-11 it's now a default behaviour to include all of the extra met along the trajectories (in the output files and in the returned data frame).
