### ISSUE TITLE
Error associated to february months

### ISSUE THREAD

**Issue by jfmendeze** [rich-iannone/SplitR#15]
Hi! I installed SplitR in a PC with windows 10 (Latin America configuration).   The problem is that when I try to run february months for (2006 - 2016) only run in 2008, 2012, 2016 due to it months have the week 5 (e.g. gdas1.feb08.w5, gdas1.feb12.w5, gdas1.feb16.w5). Is there any way or method that I can use to solve it. Thank you so much for your help.

**Comment by rich-iannone** [comment]
This is now fixed.
