### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Neeldip** [rich-iannone/SplitR#16]
I am using R version 3.4.3 and RStudio 1.1.383
The package is not available in CRAN. I have used devtools::install_github("rich-iannone/SplitR") to install.
I am getting the following error. Kindly help me out.

Downloading GitHub repo rich-iannone/SplitR@master
from URL https://api.github.com/repos/rich-iannone/SplitR/zipball/master
Installing SplitR
Installing 1 package: downloader
Installing package into ‘C:/Users/neeld/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/downloader_0.4.zip'
Content type 'application/zip' length 22349 bytes (21 KB)
downloaded 21 KB

package ‘downloader’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\neeld\AppData\Local\Temp\Rtmp8SyZxu\downloaded_packages
Installing 1 package: ggmap
Installing package into ‘C:/Users/neeld/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
also installing the dependencies ‘proto’, ‘RgoogleMaps’, ‘png’, ‘rjson’, ‘jpeg’, ‘geosphere’

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/proto_1.0.0.zip'
Content type 'application/zip' length 466858 bytes (455 KB)
downloaded 455 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/RgoogleMaps_1.4.1.zip'
Content type 'application/zip' length 959090 bytes (936 KB)
downloaded 936 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/png_0.1-7.zip'
Content type 'application/zip' length 291037 bytes (284 KB)
downloaded 284 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/rjson_0.2.15.zip'
Content type 'application/zip' length 564436 bytes (551 KB)
downloaded 551 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/jpeg_0.1-8.zip'
Content type 'application/zip' length 229358 bytes (223 KB)
downloaded 223 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/geosphere_1.5-7.zip'
Content type 'application/zip' length 891762 bytes (870 KB)
downloaded 870 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/ggmap_2.6.1.zip'
Content type 'application/zip' length 4562608 bytes (4.4 MB)
downloaded 4.4 MB

package ‘proto’ successfully unpacked and MD5 sums checked
package ‘RgoogleMaps’ successfully unpacked and MD5 sums checked
Warning: unable to move temporary installation ‘C:\Users\neeld\Documents\R\win-library\3.4\file259c16c13496\RgoogleMaps’ to ‘C:\Users\neeld\Documents\R\win-library\3.4\RgoogleMaps’
package ‘png’ successfully unpacked and MD5 sums checked
package ‘rjson’ successfully unpacked and MD5 sums checked
package ‘jpeg’ successfully unpacked and MD5 sums checked
package ‘geosphere’ successfully unpacked and MD5 sums checked
package ‘ggmap’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\neeld\AppData\Local\Temp\Rtmp8SyZxu\downloaded_packages
Installing 1 package: leaflet
Installing package into ‘C:/Users/neeld/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
also installing the dependencies ‘gridExtra’, ‘crosstalk’, ‘viridis’

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/gridExtra_2.3.zip'
Content type 'application/zip' length 1084626 bytes (1.0 MB)
downloaded 1.0 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/crosstalk_1.0.0.zip'
Content type 'application/zip' length 599227 bytes (585 KB)
downloaded 585 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/viridis_0.4.1.zip'
Content type 'application/zip' length 1754972 bytes (1.7 MB)
downloaded 1.7 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/leaflet_1.1.0.zip'
Content type 'application/zip' length 2528363 bytes (2.4 MB)
downloaded 2.4 MB

package ‘gridExtra’ successfully unpacked and MD5 sums checked
package ‘crosstalk’ successfully unpacked and MD5 sums checked
package ‘viridis’ successfully unpacked and MD5 sums checked
package ‘leaflet’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\neeld\AppData\Local\Temp\Rtmp8SyZxu\downloaded_packages
"C:/PROGRA~1/R/R-34~1.3/bin/x64/R" --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  "C:/Users/neeld/AppData/Local/Temp/Rtmp8SyZxu/devtools259c393c7b/rich-iannone-SplitR-d915bf5"  \
  --library="C:/Users/neeld/Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'SplitR' ...
** R
** data
** inst
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'RgoogleMaps'
ERROR: lazy loading failed for package 'SplitR'
* removing 'C:/Users/neeld/Documents/R/win-library/3.4/SplitR'
In R CMD INSTALL
Installation failed: Command failed (1)

**Comment by wjjxjd** [comment]
You should installed at R=3.6

**Comment by rich-iannone** [comment]
The `RgoogleMaps` package is no longer a dependency so installation should no longer have this specific problem.
