### ISSUE TITLE
hysplit_trajectory error: object 'run_type' not found

### ISSUE THREAD

**Issue by lyggd** [rich-iannone/SplitR#19]
Hello 
I have Error in running hysplit_trajectory  for 2015 to 2017.
I download the NARR data from 12/2014 to 1/2018 and here is my code
```
trajectory <- 
  hysplit_trajectory(
    lat = 32.6903,
    lon = -114.6144,
    height = 10,
    duration = 48,
    run_period = c(2015, 2016, 2017),
    daily_hours = c(0, 6, 12, 18),
    direction = "backward",
    met_type = "narr",
    extended_met = FALSE) 
```
I got the error message "Error: object 'run_type' not found". 
But if I set `run_period = c(2015, 2016)` , it works OK.
Could you help me figure out this solution?
Thanks a lot
Yi

**Comment by rich-iannone** [comment]
The `run_type` argument is now gone. Now, for trajectory runs, we expect a vector of dates in the `days` argument.
