### ISSUE TITLE
Error with Feb meteorological data for HYSPLIT trajectory

### ISSUE THREAD

**Issue by jia-11** [rich-iannone/SplitR#2]
I encountered following error when running HYSPLIT trajectory for Feb., 2011 using hysplit_trajectory. It tries to download gdas1.feb11.w5 file which does not exist for February.

> trying URL 'ftp://arlftp.arlhq.noaa.gov/archives/gdas1/gdas1.feb11.w5'
> using Synchronous WinInet calls
> Error in download.file(url = paste0("ftp://arlftp.arlhq.noaa.gov/archives/gdas1/",  : 
>   cannot open URL 'ftp://arlftp.arlhq.noaa.gov/archives/gdas1/gdas1.feb11.w5'
> In addition: Warning message:
> In download.file(url = paste0("ftp://arlftp.arlhq.noaa.gov/archives/gdas1/",  :
> InternetOpenUrl failed: ''

**Comment by rich-iannone** [comment]
@jia-11 I'll look into this and make sure these February cases don't cause any more problems.

**Comment by jokejazz** [comment]
Hello Rihc, I hav tried the packages and it shows an error at the end of the run. I have tried it on both windows and linux with the same errors. I have attached a screen grab of the errors. How do I move past this? I  have a registerd HYSPLIT account in case I need to insert my account name and password somewhere for url access. 
![splitr2016-05-11_171915](https://cloud.githubusercontent.com/assets/19322420/15208101/b5b3c8d4-1821-11e6-9b2c-9992813e9361.png)

**Comment by rich-iannone** [comment]
This is something I'm recently aware of and will be fixed soon. (No need for account information to fix.) I'll report back here once this is solved.

**Comment by rich-iannone** [comment]
For trajectory runs, the February issue has been solved.

Here's an example (takes awhile to run) that runs twice daily across 25 receptor sites for all of February 2012:

```r
library(SplitR)
library(lubridate)
library(here)

traj_model <- 
  create_traj_model() %>%
  add_grid(
    lat = 49.0,
    lon = -123.0,
    range = c(0.8, 0.8),
    division = c(0.2, 0.2)
  ) %>%
  add_params(
    height = 50,
    duration = 6,
    days = seq(ymd("2012-02-01"), ymd("2012-02-28"), by = "1 day"),
    daily_hours = c(0, 12),
    direction = "backward",
    met_type = "gdas1",
    met_dir = here::here("met"),
    exec_dir = here::here("out")
  ) %>%
  run_model()
```

**Comment by noraini0210** [comment]
Hi 

I am facing similar problem in R.  It tries to download gdas1.feb15.w5 file which does not exist for February. 

I run:
traj_model <- 
  create_traj_model() %>%
  add_grid(lat = 6.0086,lon = 102.4259,range = c(0.8, 0.8),division = c(0.2, 0.2)) %>%
  add_params(
    height = 30,
    duration = 120,
    run_period = c("2015-02-01","2015-02-28"), 
    daily_hours = c(0, 6, 12, 18),
    direction = "backward",
    met_type = "gdas1",
    met_dir = "C:/GDAS/",
    exec_dir = "c:/hysplit4/working.559"
  ) %>%
  run_model()

However, I still encountered error as followed:

trying URL 'ftp://arlftp.arlhq.noaa.gov/archives/gdas1/gdas1.feb15.w4'
downloaded 571.1 MB

trying URL 'ftp://arlftp.arlhq.noaa.gov/archives/gdas1/gdas1.feb15.w5'
Error in download.file(url, ...) : 
  cannot open URL 'ftp://arlftp.arlhq.noaa.gov/archives/gdas1/gdas1.feb15.w5'
In addition: Warning message:
In download.file(url, ...) : InternetOpenUrl failed: ''
