### ISSUE TITLE
Write out fail for dispersion.csv on windows

### ISSUE THREAD

**Issue by bhickson** [rich-iannone/splitr#22]
When attempting to create dispersion model as per sample instructions from README, write out fails with error...

`Error in file(file, ifelse(append, "a", "w")) : 
  cannot open the connection
In addition: Warning message:
In file(file, ifelse(append, "a", "w")) :
  cannot open file '"C:/Users/myname/Documents/SplitR/disp--2018-07-12--15-41-50/dispersion.csv"': Invalid argument`

Replacing line 815->817 in `hysplit_dispersion.R` with

`write.table(disp_df, file = paste0(getwd(), "/", folder_name, "/dispersion.csv"), sep = ",", row.names = FALSE)` 

solved the issue. Just remove the escape characters and quotes in beginning and end of paste0. 

Verified on two Windows 10 machines.

**Comment by rich-iannone** [comment]
Thanks for filing this issue. I will address this by using `file.path()`. I intend to refactor the `hysplit_dispersion()` function.

**Comment by rich-iannone** [comment]
This shouldn’t be a problem anymore given the recent changes to `hysplit_dispersion()`.
