### ISSUE TITLE
trajectory_plot() issue

### ISSUE THREAD

**Issue by jwsaf** [rich-iannone/SplitR#23]
Hi there

Nothing is plotted. What am I doing wrong?

Here's my code:

library(devtools)
devtools::install_github("rich-iannone/SplitR", force=TRUE)

library(SplitR)  

library(magrittr)

setwd("C:/Users/User/Documents/R/win-library/3.5/SplitR")  

trajectory_model <-
  create_traj_model() %>%
  add_grid(
    lat = -25.7,   # Pretoria
    lon = 28.2,
    range = c(0.8, 0.8),
    division = c(0.2, 0.2)) %>%
  add_params(
    height = 50,
    duration = 6,
    run_period = "2017-04-01",
    daily_hours = c(0, 12),
    direction = "backward",
    met_type = "reanalysis") %>%
  run_model()

# Get a data frame containing the model results
trajectory_df <-
  trajectory_model %>% get_output_df()

trajectory_df

# Plot results using the trajectory model object
trajectory_model %>% trajectory_plot()

**Comment by wjjxjd** [comment]
Me too

**Comment by rich-iannone** [comment]
This was given some attention recently and fixes were made to make this work again. Please open another issue if this indeed doesn’t work (closing for now).
