### ISSUE TITLE
Help with the version

### ISSUE THREAD

**Issue by andreacardozov96** [rich-iannone/SplitR#30]
I need some help, i dont know what to do when this appearce

devtools::install_github("rich-iannone/SplitR")
Downloading GitHub repo rich-iannone/SplitR@master
These packages have more recent versions available.
Which would you like to update?

1:   glue (1.3.0 -> 1.3.1) [CRAN]

Enter one or more numbers separated by spaces, or an empty line to cancel
1:

**Comment by rich-iannone** [comment]
Sorry for the late response to this. When the installing function asks for updates, it's usually safe and advised to update all packages. In this specific case, typing `1` and ENTER would have been okay to do.
