### ISSUE TITLE
trajectory_read.R for variable header lengths

### ISSUE THREAD

**Issue by hawkinsEPA** [rich-iannone/SplitR#32]
The following logic is needed for trajectory_read.R to correctly read in trajectory files with differing variable header lengths using the expanded met fields.  Without this the code will error here:  
traj_df <- cbind(traj_df, traj_extra_df)

Fix is below... add in code starting at line 206...
206,220c206
<          traj_temp <- try(
<       read.fwf(paste0(path.expand(output_folder),
<                       "/", trajectory_file_list[i]),
<                widths = column_widths)
<     )
<
<     if(class(traj_temp)!="try-error") {
<       for (j in 1:nrow(traj_temp)) {
<         if (length(grep("PRESS",
<                         traj_temp[j,2])) != 0) {
<           skip_up_to_line <- j
<         }
<       }
<     }
<

**Comment by rich-iannone** [comment]
Hello. Sorry for the use of `cbind()`. Was not a good idea. I’ve recently changed this so that the code uses a `dplyr::right_join()`.
