### ISSUE TITLE
Error in strsplit(grids$heights, split = " ") : non-character argument

### ISSUE THREAD

**Issue by wjjxjd** [rich-iannone/SplitR#33]
> dispersion_model <-
+     create_disp_model() %>%
+     add_emissions(
+         rate = 5,
+         duration = 6,
+         start_day = "2015-07-01",
+         start_hour = 0) %>%
+     add_species(
+         pdiam = 1,
+         density = 1,
+         shape_factor = 1) %>%
+     add_grid(
+         range = c(0.5, 0.5),
+         division = c(0.1, 0.1)) %>%
+     add_params(
+         lat = 49.0,
+         lon = -123.0,
+         height = 50,
+         duration = 24,
+         start_day = "2015-07-01",
+         start_hour = 0,
+         direction = "forward",
+         met_type = "reanalysis") %>%
+     run_model()
trying URL 'ftp://arlftp.arlhq.noaa.gov/archives/reanalysis//RP201506.gbl'
downloaded 113.6 MB

trying URL 'ftp://arlftp.arlhq.noaa.gov/archives/reanalysis//RP201507.gbl'
downloaded 117.4 MB

trying URL 'ftp://arlftp.arlhq.noaa.gov/archives/reanalysis//RP201508.gbl'
downloaded 117.4 MB

Error in strsplit(grids$heights, split = " ") : non-character argument
hello I made this mistake while using the example

**Comment by rich-iannone** [comment]
Sorry about this error. However, it is now fixed!
