### ISSUE TITLE
no back-trajectory across month

### ISSUE THREAD

**Issue by IsotopeGuy** [rich-iannone/splitr#43]
Dear Richard, 
thank You for a beautiful package, it helps me a lot in my research. 
Please help me with this error: when trying to run 10-days trajectories, I always fail at the beginning of month with error code 900, only after 10th of the month I get a trajectory. Did I miss something? Or I should extend the trajectories manually to preceding month? Here below is my code with the error msg.
Thanks in advance, Rasto.

> trajectory <-
+       hysplit_trajectory(
+         lat = "48.752",
+         lon = "19.158",
+         height = 597,
+         duration = 240,
+         met_type = "reanalysis",
+         vert_motion = 0,
+         model_height = 20000,
+         extended_met = TRUE,
+         direction = "backward",
+         days = "2016-02-01",
+         daily_hours = 12)

trying URL 'ftp://arlftp.arlhq.noaa.gov/archives/reanalysis/RP201601.gbl'
downloaded 117.4 MB

Error in .f(.x[[i]], ...) : object 'year' not found
In addition: Warning message:
In shell(sys_cmd) :
  '(cd "C:/Users/rasto/Documents" && "C:/Users/rasto/Documents/R/win-library/3.5/splitr/win/hyts_std.exe" > NUL 2>&1)' execution failed with error code 900

**Comment by rich-iannone** [comment]
Fixed by #47
