### ISSUE TITLE
Error with file.copy when computing trajectories with 3.6.1 R version but not with 3.4.4

### ISSUE THREAD

**Issue by esanchezsanchez** [rich-iannone/splitr#49]
Hi: I performed some trajectories nicely four months ago, but not an error appears now such as
"In file.copy(from = file.path(exec_dir, trajectory_files), to = recep_file_path,  :
  problem to copy working/traj--fwd-12-03-12-00-1lat_42p83752_lon_-80p30364-hgt_50-24h to working/1/traj-2020-03-11-21-36-18/traj--fwd-12-03-12-00-1lat_42p83752_lon_-80p30364-hgt_50-24h: such file does not exist"
But with previous version (3.4.4) worked perfectly. Anybody knows how to solve this problem? I tried to downgrade my R version (I use Ubuntu, now 19.10, then 19.04). Thanks a lot in advance.

**Comment by esanchezsanchez** [comment]
I have been finally able to run the model with newer version of ubuntu and R. The key aspect is to install https://packages.ubuntu.com/disco/libgfortran3, which is not installed by default on the system

**Comment by esanchezsanchez** [comment]
Solved installing libgfortran3 on the last ubuntu distribution

**Comment by Mattz-17** [comment]
Hello Sir. I encountered the same problem on my end. However, I am using Windows 10 with R version 4.0.4. How would I solve this problem as I am quite new to programming? 
Thank you.
