### ISSUE TITLE
SplitR on UNIX Cluster

### ISSUE THREAD

**Issue by jdossgollin** [rich-iannone/SplitR#5]
Hi @rich-iannone,

I'm trying to run on a cluster because I have a fairly large number of trajectories I want to run. If I run a simple script, 

```R
library(SplitR)
hysplit_trajectory()
```

I see that the `.gbl` files download without trouble, but then I get an error message

```
sh: {MYPATH}/rpackages/SplitR/osx/hyts_std: cannot execute binary file
```

Clearly the cluster is having trouble executing the HYSPLIT binaries in the `Splitr/osx` folder. 
This may be an issue on my end and I can talk to the server people about it but I wanted to ask if you had seen something like this before.

**Comment by jdossgollin** [comment]
fwiw the `MYPATH` isn't in the output, I just didn't want to post the whole file path

**Comment by rich-iannone** [comment]
James,

The cluster is probably using Redhat Linux, so the Mac OS X binaries won’t work. Do you have access to Linux-compiled binaries of HYSPLIT? If so, I could include those in SplitR. Then your runs would likely work!

Best,
Rich

**Comment by jdossgollin** [comment]
Sure, makes sense -- I see in the `hysplit_trajectory` that all UNIX systems use the OSX binaries. The Red Hat guess is spot on as well. From a coding perspective, is it better to include compiled binaries in the `SplitR` package or to compile them locally?

**Comment by rich-iannone** [comment]
It would probably be easier for the end-user if the binaries were to be included in the package. It's easy enough to detect that R is running in Linux and then use the correct binaries. I'll take a look at compiling some HYSPLIT from source for x86 Linux.

**Comment by jdossgollin** [comment]
OK, I just reached out to the guy that the HYSPLIT web site says is in
charge of distributing linux binaries

On Thu, Mar 24, 2016 at 12:35 PM Richard Iannone <notifications@github.com>
wrote:

> It would probably be easier for the end-user if the binaries were to be
> included in the package. It's easy enough to detect that R is running in
> Linux and then use the correct binaries. I'll take a look at compiling some
> HYSPLIT from source for x86 Linux.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/rich-iannone/SplitR/issues/5#issuecomment-200915583>
>
-- 
James Doss-Gollin

james.dossgollin@gmail.com
james.doss-gollin@columbia.edu
Skype: james.doss.gollin

**Comment by jdossgollin** [comment]
@rich-iannone thanks for addressing this -- saw you updated.

If I run
```
with_libpaths(new = "/********/rpackages", install_github('SplitR'))
library(SplitR)
hysplit_trajectory()
```
I'm still getting the 
```
/hmt/*********/R/x86_64-redhat-linux-gnu-library/3.2/SplitR/osx/hyts_std: cannot execute binary file
```

do I need to change something so it's not looking for the binaries in the `osx` folder?

**Comment by rich-iannone** [comment]
While the linux binaries are indeed available in the package itself, I do have to build in the detection of the OS. I will do that v. soon. (Then I'll have to test this on a Linux partition to make sure it works!)

**Comment by jdossgollin** [comment]
Jumped the gun! Don't rush for my sake, I have a rough week ahead anyways. Thanks

**Comment by rich-iannone** [comment]
It's okay! But I'll totally get back to it because I'm keen to have the trajectory models working on three platforms.

**Comment by rich-iannone** [comment]
Alright @jdossgollin , there is now support for Linux in **SplitR**. However, take note of the argument names: I've just made them shorter so you'll have to modify calls to `hysplit_trajectory` with a lot of find and replace.

**Comment by jdossgollin** [comment]
Cool!
