### ISSUE TITLE
Hysplit executable not running on rocker:3.6.3

### ISSUE THREAD

**Issue by audiracmichelle** [rich-iannone/splitr#62]
Probable reason - rocker builds on Debian:9. Fortran 3 cannot be installed

**Comment by juliombarros** [comment]
Hi, had the same issue on Ubuntu 20.4
Solution: https://gist.github.com/sakethramanujam/faf5b677b6505437dbdd82170ac55322

**Comment by rich-iannone** [comment]
Closed with https://github.com/rich-iannone/splitr/pull/63.
