### ISSUE TITLE
Dispersion Model Error - "dir" is missing

### ISSUE THREAD

**Issue by c422j381** [rich-iannone/SplitR#8]
When I run the create_disp_model example, I get an error that "dir" is missing, with no default.  I am running the example code : 

dispersion_model <- 
    create_disp_model(name="crystal_clean") %>%
  add_emissions(
      rate = 5,
      duration = 6,
      start_day = "2016-07-18",
      start_hour = 0) %>%
  add_species(
    pdiam = 1,
    density = 1,
    shape_factor = 1) %>%
  add_grid(
    range = c(0.5,0.5),
    division = c(0.1,0.1)) %>%
  add_params(
    lat = 49.0,
    lon = -123.0,
    height = 10,
    duration = 24,
    start_day = "2016-07-18",
    start_hour = 0,
    direction = "forward",
    met_type = "gdas1")
  
run_model(dispersion_model)

and I get the following error : 

Error in paste0(dir, "/", "SETUP.CFG") : 
  argument "dir" is missing, with no default

**Comment by rich-iannone** [comment]
I'll take a look at this. Thanks for filing this issue!

**Comment by rich-iannone** [comment]
@c422j381 This should be fixed now. Please reopen the issue if there's still a problem.
